---
title: "Your Title Here"
author: "Your Name"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include = FALSE, echo = FALSE}
library(tidyverse)
library(lubridate)
library(gt)
library(paletteer)
library(plotly)
library(flexdashboard)

#Working directory for .RMD
knitr::opts_knit$set(echo = TRUE,
                     root.dir = rprojroot::find_rstudio_root_file())

#Controlling figure output in markdown
knitr::opts_chunk$set(
#  fig.height =   
  fig.width = 6,
#  fig.asp = .5,
  out.width = "90%",
#  out.height = 
 fig.align  = "center",
  cache = FALSE,
  eval  = TRUE,
  echo  = TRUE,
  warning = FALSE
)

#My Colours (from viridis)
my_purple <- "#440154FF"
my_yellow <- "#FDE725FF"

#Set Theme for ggplot2
theme_set(theme_bw() + theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom"))

#Set Scientific notation output and decimal places for knitr
options(scipen = 999)
options(digits = 4)
options(dplyr.summarise.inform = FALSE)
```


```{r data_read, include = FALSE}
#Read in the nyc airbnb data set
nyc_airbnb.df <- read_csv("./data/nyc_airbnb.csv", show_col_types = FALSE) %>%
  mutate(rating = review_scores_location / 2) %>%
  filter(
    neighbourhood_group %in% "Manhattan",
    room_type %in% "Entire home/apt",
    (!is.na(rating)),
    price <= 1000
  ) %>%
  dplyr::select(neighbourhood, rating, price,
                room_type, lat, long, contains("review"))
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
data(mtcars)
hist(mtcars$mpg)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
hist(mtcars$cyl)
```

### Chart C

```{r}
hist(mtcars$disp)
```

