---
title: "Flexdashboard 2"
author: "Brett Weaver"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include = FALSE, echo = FALSE}
library(ggthemes, quietly = TRUE)
library(osmdata)
library(tidyverse)
library(ggmap)
library(sf)
library(viridis, quietly = TRUE)
library(gt)
library(leaflet)
library(tidycensus)
library(plotly)
library(flexdashboard)

#Working directory for .RMD
knitr::opts_knit$set(echo = TRUE,
                     root.dir = rprojroot::find_rstudio_root_file())

#Controlling figure output in markdown
knitr::opts_chunk$set(
#  fig.height =   
  fig.width = 6,
#  fig.asp = .5,
  out.width = "90%",
#  out.height = 
 fig.align  = "center",
  cache = FALSE,
  eval  = TRUE,
  echo  = TRUE,
  warning = FALSE,
  message = FALSE
)

#My Colours (from viridis)
my_purple <- "#440154FF"
my_yellow <- "#FDE725FF"

#Set Theme for ggplot2
theme_set(theme_bw() + theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom"))

#Set Scientific notation output and decimal places for knitr
options(scipen = 999)
options(digits = 4)
options(dplyr.summarise.inform = FALSE)
```


{data-width=650}
-----------------------------------------------------------------------

### Chart 1: Location and Information of Shops in Minnesota

```{r plot 1 - shops, echo = FALSE, fig.height = 4, fig.width = 4}

#Grabbing Minnesota shops
osm_shop_sf.df <- opq(bbox = "minnesota") %>%
  add_osm_feature(key = "shop", value = c("toys", "wine", "music", "furniture")) %>%
  osmdata_sf()


#Extract the relevent sf data frame
shop_points.df <- osm_shop_sf.df$osm_points %>% 
  janitor::clean_names() %>%
  filter(!is.na(shop)) %>% #only retain 'valid' tags
  dplyr::select(osm_id, name, shop, opening_hours, phone, website, geometry) %>%
  mutate(shop = str_to_title(shop) %>% 
           as_factor())

#Extract the levels/order of shop type factor
shop_types <- levels(shop_points.df$shop)
n_types    <- length(shop_types)

#Initialize our colour pallete (discrete in this case)
my_pallete <- colorFactor(viridis_pal(option = "D")(n_types), domain = shop_types)


#Need html tools to get our labels to render appropriately
library(htmltools, quietly = TRUE)

#Add a text label like normal
shop_label.df <- shop_points.df %>%
  mutate(
    text_label = str_c(
      name,
      "<br/>Store Type: ",
      shop,
      "<br/>Open Hours: ",
      opening_hours,
      "<br/>Phone: ",
      phone,
      "<br/>Website: ",
      website
    )
  )

#Redisplay the leaflet
leaflet(data = shop_label.df) %>%
  addProviderTiles('CartoDB.Positron') %>% 
  addCircleMarkers(
    color   = ~my_pallete(shop_types),
    label   = ~map(text_label, HTML), #map over labels, make html
    opacity = 0.4, #alpha
    weight  = 2, #outline strength
    radius  = 4 #size of circle
  ) %>%
  addLegend(
    title    = "Store Type",
    position = "bottomright",
    colors   = viridis_pal(option = "D")(n_types),
    labels   = shop_types 
  )

```

{data-width=350}
-----------------------------------------------------------------------

### Chart 2: ACS Hennepin County Population

```{r plot 2 - population, echo = FALSE, fig.height = 4, fig.width = 2}
census_api_key("1df0a4b6fe999bc2506228837ee20dab3eee9f9a")

options(tigris_use_cache = TRUE)

#Call the ACS API, returns a sf object
mn_pop.df <- get_acs(
  geography = "tract",
  variables = "B01003_001E", #Code for income at or above poverty level
  state     = "MN",
  county    = "Hennepin",
  year      = 2020,
  geometry  = TRUE
)


#Add a text label to mn_poverty.df
mn_pop_plotly.df <- mn_pop.df %>%
  mutate(
    tract      = str_split(NAME, ",") %>%
      map_chr(1) %>%
      str_remove("Census Tract "),
    text_label = str_c(
      "Tract: ",
      tract,
      "\nPopulation Total: ",
      scales::number(estimate)
    )
  )

#Get the bounding box and county outline
mn.box           <- osmdata::getbb("minnesota")
hennepin.box     <- osmdata::getbb("hennepin")
hennepin.outline <- osmdata::getbb("hennepin", format_out = "polygon")[[1]] %>%
  as_tibble() %>%
  rename(longitude = V1, latitude = V2)


#Get map from ggmap
#Get the base map (foundational layer)
mn_base.map <- get_map(
  location = hennepin.box,
  source   = "google",
  maptype  = "roadmap",
  crop = TRUE
)

#Create the base map
hennepin_base.gg <- ggmap(mn_base.map) +
  geom_polygon(data = hennepin.outline, aes(x = longitude, y = latitude), 
               colour = "black", size = 1.6, alpha = 0.1) +
  theme_map() +
  theme(
    plot.title   = element_text(size  = 16,
                                hjust = 0.5),
    legend.text  = element_text(size = 16),
    legend.title = element_text(size = 16),
    legend.position = "right"
  )


coord_ggmap <- st_crs(hennepin_base.gg) #NA
coord_sf    <- st_crs(mn_pop_plotly.df) #NAD83

#Overlay the sf info from tidycensus ACS income estimates
mn_pop.ggmap <- hennepin_base.gg +  
  geom_sf(data = mn_pop_plotly.df, 
          aes(fill = estimate, text = text_label),
          colour = "black", size = 0.1,
          inherit.aes = FALSE) + 
  labs(title = "Hennepin County, MN 2020 ACS Total Population") + 
  scale_fill_viridis_c("Population", labels = scales::number) +
  theme_map() +
  theme(
    plot.title   = element_text(size  = 16,
                                hjust = 0.5),
    legend.text  = element_text(size = 16),
    legend.title = element_text(size = 16),
    legend.position = "right"
  )

#Display plotly
ggplotly(mn_pop.ggmap,
         tooltip = "text",
         height  = 400,
         width   = 400) %>%
  style(hoveron = "fills")

```

### Chart 3: Percentage of Sex by County in MN 

```{r plot 3 - sex, echo = FALSE, fig.height = 6, fig.width = 5}
mn.df <- st_read("./data/USA_Counties/USA_Counties.shp", quiet = TRUE) %>%
  janitor::clean_names() %>%
  filter(state_name %in% "Minnesota")


mn_sex.gg <- mn.df %>%
  dplyr::select(name, males, females, geometry) %>%
  rename(county = name) %>%
  pivot_longer(
    cols      = contains(c("males")), #tidy long data by category
    names_to  = "sex",
    values_to = "sex_total"
  ) %>%
  group_by(county) %>% #County level population
  mutate(county_pop = sum(sex_total),
         sex = str_to_title(sex)) %>%
  group_by(county, sex) %>%
  summarise(
    perc_sex = sex_total / county_pop,
    geometry  = geometry
  ) %>%
  ungroup() %>%
  nest(data = c("sex", "perc_sex", "geometry")) %>%
  mutate(
    text_label = map_chr(.x = data, 
                         ~str_c(
                           "\n",
                           .x$sex,
                           ": ", 
                           scales::percent(.x$perc_sex, accuracy = 0.01),
                           collapse = ""
                         )
    )
 #   text_label = str_c(county, "\nSex", text_label, "\nPercent: ", scales::percent(perc_sex, accuracy = 0.01))
  ) %>%
  unnest(data) %>%
  mutate(
    text_label = str_c(county, "\nSex", text_label)
  ) %>% 
  st_as_sf() %>%
  ggplot() +
  geom_sf(aes(fill = perc_sex, text = text_label),
          colour = "black", size = 0.8, alpha = 0.6) +
  labs(
    title = "2017 MN ACS Percent Sex by County" 
  ) +
  scale_fill_viridis_c("Percent Sex", labels = scales::percent) +
  theme_map() +
  theme(
    plot.title   = element_text(size  = 24,
                                hjust = 0.5),
    legend.text  = element_text(size = 20),
    legend.title = element_text(size = 20),
    legend.position = "right"
  ) +
  facet_wrap(~ sex, scales = "fixed")


#Plotly
ggplotly(mn_sex.gg, 
         tooltip = "text",
         height  = 400,
         width   = 400) %>%
  style(hoveron = "fills")


```

